### ISSUE TITLE
Executable aws not found

### ISSUE THREAD

**Issue by swananddhole** [actions-hub/kubectl#16]
I'm using the latest version and using KUBE_CONFIG way, but getting bellow error. Can somebody help me out here.
```
Unable to connect to the server: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

Here is how I'm using the action - 
```
      - name: Setup kubectl
        uses: actions-hub/kubectl@v1.25.4
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
```
