### ISSUE TITLE
How to annotate deployment?

### ISSUE THREAD

**Issue by darren** [actions-hub/kubectl#26]
Tried these:

### direct reference to github.event
```yaml
      - name: Annotate
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
           args: annotate deployment/thttpd kubernetes.io/change-cause="${{ github.event.head_commit.message }}"
```
got error: 

`error: all resources must be specified before annotation changes: commit messsage`

BTW:  `{{github.event.head_commit.message}}` has an extra `\n`.

### use env 
```yaml
      - name: Annotate
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          COMMIT: ${{ github.event.head_commit.message }}
        with:
          args: annotate deployment/thttpd kubernetes.io/change-cause="${COMMIT}"
```
the above left  these in rollout history:
```
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
3         <none>
4         <none>
5         ${COMMIT}
6         ${COMMIT}
7         ${COMMIT}
8         ${COMMIT}
9         ${COMMIT}
10        ${COMMIT}
11        ${COMMIT}
```
