### ISSUE TITLE
Input `redirect-to` is not working

### ISSUE THREAD

**Issue by alewkinr** [actions-hub/kubectl#27]
Hello there!

I’m trying to extract secret from k8s using this GH action, but the problem that I can not access the command output.

I checked the `actions.yaml` there is an undocumented input `redirect-to` which seems not working properly.

Here is the example:
```
steps:
  - name: Get secrets
    id: get-secret
    uses: actions-hub/kubectl@v1.28.2
    env:
     KUBE_HOST: ${{ env.KUBE_HOST }}
     KUBE_CERTIFICATE: ${{ env.KUBE_CERTIFICATE }}
     KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
    with:
     args: get secret ${{ inputs.secret-name }} -n ${{ inputs.namespace }} -o json
     redirect-to: secret-content
  
  - name: Print result
    shell: bash
    run: echo "${{ steps.get-secret.outputs.secret-content }}"
```

And that is debug output:
```
[GitHub Actions Debug Workflow/actions-debug] [DEBUG] expression 'echo "${{ steps.get-secret.outputs.secret-content }}"' rewritten to 'format('echo "{0}"', steps.get-secret.outputs.secret-content)'
[GitHub Actions Debug Workflow/actions-debug] [DEBUG] evaluating expression 'format('echo "{0}"', steps.get-secret.outputs.secret-content)'
[GitHub Actions Debug Workflow/actions-debug] [DEBUG] expression 'format('echo "{0}"', steps.get-secret.outputs.secret-content)' evaluated to '%!t(string=echo "")'
```

Executing github action locally with: https://github.com/nektos/act
