### ISSUE TITLE
How to pass manifest file to command

### ISSUE THREAD

**Issue by AleksaRistic216** [actions-hub/kubectl#31]
I am trying to create job like this:

```
  apply-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    needs: apply-resources
    steps:
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f src/k8s/services/my-service.yml
```

but getting error that file does not exist.

Is it possible to pass manifest file here somehow?

**Comment by adriantombu** [comment]
You probably had an answer since last year, but for whoever encounters this problem too and ends up on this issue (I was that person 10 minutes ago), you need to **checkout your repository** with `actions/checkout@v4` before trying to apply your manifest changes.


For you, this would look like below:

```yaml
  apply-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f src/k8s/services/my-service.yml
```

I hope this will help at least one person on this patatoid we call home 🫡
