### ISSUE TITLE
Unable to connect to the server: getting credentials: exec: executable aws not found

### ISSUE THREAD

**Issue by shimon-elbaz** [actions-hub/kubectl#6]
tried to use this action , started with simple "get pods" command.
keep getting the above error and the following description:

```
Unable to connect to the server: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

this is my code:
```
      - name: Rollout Changes In Kubernetes Cluster
        if: ${{github.ref == 'refs/heads/master'}}
        # Load the KubeConfigs from secrets and run the rollout command
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.AWS_KUBECONFIG}}
        with:
          args: get pods
```

running my action on ubuntu-latest.

the kubeconfig is base64 encoded , using it to connect to am AWS EKS cluster.
using the same config file on my computer works with no problem.
tried to change the command to aws2 (like seen in several posts) but that got me to the same place.

**Comment by exelban** [comment]
Hi. Thanks for the feedback.
It looks like you need to have installed `aws cli` to connect to the EKS cluster. This action does not have this cli. And I'm not sure that it will be added. The best option will be to find some AWS action and use it.

**Comment by Gajeski** [comment]
Hi I have the same error:
```
Unable to connect to the server: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```
But the aws cli is present because running 
```
aws --version
```
works and gives expected output. Github hosted VMs are supposed to have the aws cli installed and by the looks of it they do, so how can the aws exe be not present ?

Workflow code:
```
steps:
    - name: aws v check
      run: aws --version
    
    - name: Deploy to dev
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: apply -f k8s/dev/k8s.yml
    
```
